package texteditor;
/* Generated By:JavaCC: Do not edit this line. keysParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface keysParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int A = 3;
  /** RegularExpression Id. */
  int B = 4;
  /** RegularExpression Id. */
  int C = 5;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int EQUAL = 7;
  /** RegularExpression Id. */
  int VNAME = 8;
  /** RegularExpression Id. */
  int NEWLINE = 9;
  /** RegularExpression Id. */
  int INS = 10;
  /** RegularExpression Id. */
  int DEL = 11;
  /** RegularExpression Id. */
  int WRITESTR = 12;
  /** RegularExpression Id. */
  int AT = 13;
  /** RegularExpression Id. */
  int START = 14;
  /** RegularExpression Id. */
  int OF = 15;
  /** RegularExpression Id. */
  int LINE = 16;
  /** RegularExpression Id. */
  int CARET = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"alt\"",
    "\"ctrl\"",
    "\"shift\"",
    "\"+\"",
    "\"=\"",
    "<VNAME>",
    "<NEWLINE>",
    "\"insert\"",
    "\"delete\"",
    "<WRITESTR>",
    "\"at\"",
    "\"start\"",
    "\"of\"",
    "\"line\"",
    "\"caret\"",
  };

}
